FROM centos:7

RUN yum install -y git python2 python2-devel make automake gcc kernel-devel sudo
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o get-pip.py \
    && python get-pip.py \
    && rm -rf get-pip.py
RUN pip install --upgrade pip setuptools

RUN pip install -e git+https://github.com/lfit/releng-lftools.git#egg=lftools